dataset: essential_gene_knockouts_raw
evaluation_targets:
- - jurkat
  - EXOSC8
- - jurkat
  - RPL37A
- - jurkat
  - MCM6
- - jurkat
  - NELFB
- - jurkat
  - MED8
- - jurkat
  - NELFA
- - jurkat
  - CTDP1
- - jurkat
  - CCNH
- - jurkat
  - TRMT112
- - jurkat
  - MARS
- - jurkat
  - HARS
- - jurkat
  - XRN1
- - jurkat
  - MAX
- - jurkat
  - DDX10
- - jurkat
  - MEIS3
- - jurkat
  - NCBP2
- - jurkat
  - DBR1
- - jurkat
  - RPS13
- - jurkat
  - EIF2B1
- - jurkat
  - PCBP1
name: rs_accC_hepg2_jurkat_ood_ss:ns_20_2_most_pert_0.1-eval_jurkat
