dataset: essential_gene_knockouts_raw
evaluation_targets:
- - jurkat
  - WTAP
- - jurkat
  - VARS
- - jurkat
  - DDX10
- - jurkat
  - RPAP3
- - jurkat
  - ZNF236
- - jurkat
  - RPL10A
- - jurkat
  - MED27
- - jurkat
  - GTF2F2
- - jurkat
  - DDX52
- - jurkat
  - MLLT6
- - jurkat
  - FUNDC2
- - jurkat
  - EXOSC7
- - jurkat
  - DDX55
- - jurkat
  - SYMPK
- - jurkat
  - CTDP1
- - jurkat
  - UHRF1
- - jurkat
  - TAF7
- - jurkat
  - MED14
- - jurkat
  - EXOSC4
- - jurkat
  - SEH1L
name: rs_accC_jurkat_hepg2_k562_rpe1_ood_ss:ns_20_4_most_pert_0.1-eval_jurkat
