dataset: satija_IFNB_raw
evaluation_targets:
- - K562
  - IRF9
- - K562
  - STAT2
- - K562
  - IFNAR2
- - K562
  - STAT1
- - K562
  - USP18
name: rs_accC_A549_BXPC3_HAP1_HT29_K562_MCF7_ood_ss:ns_5_6_most_pert_0.2-eval_K562
