dataset: satija_IFNB_raw
evaluation_targets:
- - BXPC3
  - STAT2
- - BXPC3
  - USP18
- - BXPC3
  - JAK1
- - BXPC3
  - IFNAR2
- - BXPC3
  - TYK2
name: rs_accC_A549_BXPC3_MCF7_ood_ss:ns_5_3_most_pert_0.1-eval_BXPC3
