dataset: essential_gene_knockouts_raw
evaluation_targets:
- - hepg2
  - RPL30
- - hepg2
  - PSMD6
- - hepg2
  - EIF2S3
- - hepg2
  - MCM6
- - hepg2
  - CD3EAP
- - hepg2
  - SRP54
- - hepg2
  - CENPJ
- - hepg2
  - PSMC5
- - hepg2
  - NOP14
- - hepg2
  - SART3
- - hepg2
  - EIF2B2
- - hepg2
  - RPS18
- - hepg2
  - NUP107
- - hepg2
  - RPL9
- - hepg2
  - RPL13
- - hepg2
  - DDX41
- - hepg2
  - EIF3A
- - hepg2
  - AARS
- - hepg2
  - MRPL35
- - hepg2
  - ZC3H13
name: rs_accC_hepg2_jurkat_ood_ss:ns_20_2_most_pert_0.1-eval_hepg2
