dataset: essential_gene_knockouts_raw
evaluation_targets:
- - hepg2
  - DCUN1D5
- - hepg2
  - EIF3B
- - hepg2
  - CPSF3
- - hepg2
  - RPS6
- - hepg2
  - RPS27A
- - hepg2
  - CNOT1
- - hepg2
  - NMD3
- - hepg2
  - INTS5
- - hepg2
  - RPL9
- - hepg2
  - RPA2
- - hepg2
  - INTS8
- - hepg2
  - MED22
- - hepg2
  - INTS2
- - hepg2
  - RPL8
- - hepg2
  - GNL3
- - hepg2
  - RPL10
- - hepg2
  - MED7
- - hepg2
  - RPL7L1
- - hepg2
  - TPT1
- - hepg2
  - SNRPD3
name: rs_accC_hepg2_jurkat_ood_ss:ns_20_2_most_pert_0.1-eval_hepg2
