dataset: satija_IFNB_raw
evaluation_targets:
- - MCF7
  - IFNAR2
- - MCF7
  - TYK2
- - MCF7
  - MAPK8
- - MCF7
  - VAV1
- - MCF7
  - IRF1
name: rs_accC_A549_BXPC3_HAP1_HT29_K562_MCF7_ood_ss:ns_5_6_most_pert_0.2-eval_MCF7
