dataset: satija_IFNB_raw
evaluation_targets:
- - MCF7
  - TYK2
- - MCF7
  - ID1
- - MCF7
  - ID2
- - MCF7
  - IRF1
- - MCF7
  - VAV1
name: rs_accC_A549_BXPC3_MCF7_ood_ss:ns_5_3_most_pert_0.1-eval_MCF7
